heat_template_version: rocky
description: >
  Bond and VLAN configuration for compute nodes. comment14_0: ' The values of the following parameters are overridden by the
  entries in' comment15_0: ' network-environment.yaml'
{%- if resource_registry%}
resource_registry:
  {%- for port, port_path in resource_registry.items() %}
  {{port}}: {{port_path}}
  {%- endfor %}
{%- endif %}
parameters:
  ControlPlaneIp:
    default: ''
    description: IP address/subnet on the ctlplane network
    type: string
  ExternalIpSubnet:
    default: ''
    description: IP address/subnet on the external network
    type: string
  InternalApiIpSubnet:
    default: ''
    description: IP address/subnet on the internal API network
    type: string
  StorageIpSubnet:
    default: ''
    description: IP address/subnet on the storage network
    type: string
  StorageMgmtIpSubnet:
    default: ''
    description: IP address/subnet on the storage mgmt network
    type: string
  TenantIpSubnet:
    default: ''
    description: IP address/subnet on the tenant network
    type: string
  ManagementIpSubnet: # Only populated when including environments/network-management.yaml
    default: ''
    description: IP address/subnet on the management network
    type: string
  ExternalNetworkVlanID:
    default: 10
    description: Vlan ID for the external network traffic.
    type: number
  InternalApiNetworkVlanID:
    default: 20
    description: Vlan ID for the internal_api network traffic.
    type: number
  StorageNetworkVlanID:
    default: 30
    description: Vlan ID for the storage network traffic.
    type: number
  TenantNetworkVlanID:
    default: 50
    description: Vlan ID for the tenant network traffic.
    type: number
  ManagementNetworkVlanID:
    default: 60
    description: Vlan ID for the management network traffic.
    type: number
  ControlPlaneSubnetCidr: # Override this via parameter_defaults
    default: '24'
    description: The subnet CIDR of the control plane network.
    type: string
  ControlPlaneNetCidr:
    description: Control plane/provisioning network and mask
    type: string
  ControlPlaneStaticRoutes:
    default: []
    description: >
      Routes for the ctlplane network traffic.
      JSON route e.g. [{'destination':'10.0.0.0/16', 'nexthop':'10.0.0.1'}]
      Unless the default is changed, the parameter is automatically resolved
      from the subnet host_routes attribute.
    type: json
  StorageInterfaceRoutes:
    default: []
    description: >
      Routes for the storage network traffic.
      JSON route e.g. [{'destination':'10.0.0.0/16', 'nexthop':'10.0.0.1'}]
      Unless the default is changed, the parameter is automatically resolved
      from the subnet host_routes attribute.
    type: json
  InternalApiInterfaceRoutes:
    default: []
    description: >
      Routes for the internal_api network traffic.
      JSON route e.g. [{'destination':'10.0.0.0/16', 'nexthop':'10.0.0.1'}]
      Unless the default is changed, the parameter is automatically resolved
      from the subnet host_routes attribute.
    type: json
  TenantInterfaceRoutes:
    default: []
    description: >
      Routes for the tenant network traffic.
      JSON route e.g. [{'destination':'10.0.0.0/16', 'nexthop':'10.0.0.1'}]
      Unless the default is changed, the parameter is automatically resolved
      from the subnet host_routes attribute.
    type: json
  ControlPlaneDefaultRoute: # Override this via parameter_defaults
    description: The default route of the control plane network.
    type: string
  ExternalInterfaceDefaultRoute: # Not used by default in this template
    default: 10.0.0.1
    description: The default route of the external network.
    type: string
  ManagementInterfaceDefaultRoute: # Commented out by default in this template
    default: unset
    description: The default route of the management network.
    type: string
  DnsServers: # Override this via parameter_defaults
    default: []
    description: A list of DNS servers (2 max for some implementations) that will be added to resolv.conf.
    type: comma_delimited_list
  EC2MetadataIp: # Override this via parameter_defaults
    description: The IP address of the EC2 metadata server.
    type: string
  ComputeBond0Interface1:
    default: eno1
    description: Bond 0 interface 1 name
    type: string
  ComputeBond0Interface2:
    default: ens3f0
    description: Bond 0 interface 2 name
    type: string
  ComputeBond1Interface1:
    default: eno2
    description: Bond 1 interface 1 name
    type: string
  ComputeBond1Interface2:
    default: ens3f1
    description: Bond 1 interface 2 name
    type: string
  ComputeBondInterfaceOptions:
    default: mode=802.3ad miimon=100 xmit_hash_policy=layer3+4 lacp_rate=1
    description: The bonding_options string for the bond interface.
    type: string
  ControlPlaneMtu:
    default: 1500
    description: The maximum transmission unit (MTU) size(in bytes) that is
      guaranteed to pass through the data path of the segments in the network.
      (The parameter is automatically resolved from the ctlplane network's mtu attribute.)
    type: number
  ExternalMtu: # Override this via parameter_defaults
    default: 1500
    description: MTU value for this network.
    type: number
  InternalApiMtu: # Override this via parameter_defaults
    default: 1500
    description: MTU value for this network.
    type: number
  StorageMtu: # Override this via parameter_defaults
    default: 1500
    description: MTU value for this network.
    type: number
  StorageMgmtMtu: # Override this via parameter_defaults
    default: 1500
    description: MTU value for this network.
    type: number
  TenantMtu: # Override this via parameter_defaults
    default: 1500
    description: MTU value for this network.
    type: number
  ProvisioningMtu: # Override this via parameter_defaults
    default: 1500
    description: MTU value for this network.
    type: number
  ManagementMtu: # Override this via parameter_defaults
    default: 1500
    description: MTU value for this network.
    type: number
  DefaultBondMtu: # Override this via parameter_defaults
    default: 9000
    description: MTU value for this network.
    type: number
{%- for key, _dict in parameters.items() %}
  {{key}}:
  {%- for _key, _val in _dict.items() %}
    {{_key}}: {{_val}}
  {%- endfor %}
{%- endfor %}

resources:
  OsNetConfigImpl:
    type: OS::Heat::SoftwareConfig
    properties:
      group: script
      config:
        str_replace:
          template:
            get_file: /usr/share/openstack-tripleo-heat-templates/network/scripts/run-os-net-config.sh
          params:
            $network_config:
              network_config:
              {%- for cfg in network_config %}
              - type: {{cfg.type}}
                mtu:
                  get_param: {{cfg.mtu}}
                {%- if "name" in cfg %}
                  {%- if cfg.type == "sriov_pf" or cfg.type == "interface" %}
                name:
                  get_param: {{cfg.name}}
                  {%- else %}
                name: {{cfg.name}}
                  {%- endif %}
                {%- endif %}
                {%- if "ovs_extra" in cfg %}
                ovs_extra:
                  - str_replace:
                      template: {{cfg.ovs_extra.template}}
                      params:
                        _VLAN_TAG_:
                          get_param: {{cfg.ovs_extra.tenant_vlan_id}}
                {%- endif %}
                {%- if "device" in cfg %}
                device: {{cfg.device}}
                {%- endif %}
                {%- if "use_dhcp" in cfg %}
                use_dhcp: {{cfg.use_dhcp}}
                {%- endif %}
                {%- if "dns_servers" in cfg %}
                dns_servers:
                  get_param: {{cfg.dns_servers}}
                {%- endif %}
                {%- if "vlan_id" in cfg %}
                vlan_id:
                  get_param: {{cfg.vlan_id}}
                {%- endif %}
                {%- if "bonding_options" in cfg %}
                bonding_options:
                  get_param: {{cfg.bonding_options}}
                {%- endif %}
                {%- if "numvfs" in cfg %}
                numvfs:
                  get_param: {{cfg.numvfs}}
                {%- endif %}
                {%- if cfg.type == "sriov_pf" %}
                use_dhcp: false
                defroute: false
                nm_controlled: true
                hotplug: true
                promisc: false
                {%- endif %}
                {%- if "addresses" in cfg %}
                addresses:
                  {%- for address in cfg.addresses %}
                - ip_netmask:
                    {%- if cfg.type == "interface" or (cfg.type in ["linux_bond", "ovs_bridge"] and cfg.name in ["bond0", "br-tenant"]) %}
                    list_join:
                    - /
                    - - get_param: {{address.ip}}
                      - get_param: {{address.cidr}}
                    {%- else %}
                        get_param: {{address.ip_netmask}}
                    {%- endif %}
                  {%- endfor %}
                {%- endif %}
                {%- if "routes" in cfg %}
                routes:
                  {%- if cfg.name == "bond0" or cfg.name == "br-tenant" or cfg.type == "interface" %}
                    {%- for route in cfg.routes %}
                      {%- if 'default' in route %}
                - default: {{route.default}}
                      {%- endif %}
                      {%- if 'ip_netmask' in route %}
                - ip_netmask:
                    get_param: {{route.ip_netmask}}
                      {%- endif %}
                  next_hop:
                    get_param: {{route.next_hop}}
                    {%- endfor %}
                  {%- else %}
                  get_param: {{cfg.routes}}
                  {%- endif %}
                {%- endif %}
                {%- if 'members' in cfg %}
                members:
                  {%- for member in cfg.members %}
                  - type: {{member.type}}
                    {%- if 'name' in member %}
                      {%- if member.type == "interface" %}
                    name:
                      get_param: {{member.name}}
                      {%- else %}
                    name: {{member.name}}
                      {%- endif %}
                    {%- endif %}
                    {%- if "rx_queue" in member %}
                    rx_queue:
                      get_param: {{member.rx_queue}}
                    {%- endif %}
                    {%- if "ovs_options" in member %}
                    ovs_options:
                      get_param: {{member.ovs_options}}
                    {%- endif %}
                    {%- if "mtu" in member %}
                    mtu:
                      get_param: {{member.mtu}}
                    {%- endif %}
                    {%- if "bonding_options" in member %}
                    bonding_options:
                      get_param: {{member.bonding_options}}
                    {%- endif %}
                    {%- if "vlan_id" in member %}
                    vlan_id:
                      get_param: {{member.vlan_id}}
                    {%- endif %}
                    {%- if "device" in member %}
                    device: {{member.device}}
                    {%- endif %}
                    {%- if "addresses" in member %}
                    addresses:
                      {%- for address in member.addresses %}
                      - ip_netmask:
                          get_param: {{address.ip_netmask}}
                      {%- endfor %}
                    {%- endif %}
                    {%- if 'routes' in member %}
                    routes:
                      get_param: {{member.routes}}
                    {%- endif %}
                    {%- if "primary" in member %}
                    primary: {{member.primary}}
                    {%- endif %}
                    {%- if "members" in member %}
                    members:
                      {%- for _member in member.members %}
                    - type: {{_member.type}}
                        {%- if _member.type == 'interface' %}
                      name:
                        get_param: {{_member.name}}
                        {%- else %}
                      name: {{_member.name}}
                        {%- endif %}
                        {%- if "mtu" in _member %}
                      mtu:
                        get_param: {{_member.mtu}}
                        {%- endif %}
                        {%- if "driver" in _member %}
                      driver:
                          get_param: {{_member.driver}}
                        {%- endif %}
                        {%- if 'primary' in _member %}
                      primary: {{_member.primary}}
                        {%- endif %}
                        {%- if "members" in _member %}
                      members:
                          {%- for __member in _member.members %}
                        - type: {{__member.type}}
                          name:
                            get_param: {{__member.name}}
                          {%- endfor %}
                        {%- endif %}
                      {%- endfor %}
                    {%- endif %}
                  {%- endfor %}
                {%- endif %}
              {%- endfor %}
outputs:
  OS::stack_id:
    description: The OsNetConfigImpl resource.
    value:
      get_resource: OsNetConfigImpl
