- include: ../../powerflex-common/tasks/install_powerflex.yaml

- name: login to MDM
  command: scli --login --username admin --password "{{ password }}" --approve_certificate
  run_once: true
  delegate_to: "{{ powerflex_config_ip }}"

- name: add SDS if a dedicated netork for rebuild/rebalance is required
  command: >
    scli --add_sds 
    --sds_ip {{ hostvars[inventory_hostname]['ansible_'+cluster_interface]['ipv4']['address'] }},{{ hostvars[inventory_hostname]['ansible_'+rebuild_interface]['ipv4']['address'] }}
    --sds_ip_role sds_only,sdc_only
    --storage_pool_name {{ storage_pool }} 
    --sds_name {{ hostvars[inventory_hostname]['ansible_hostname'] }} 
    --protection_domain_name {{ protection_domain }} 
    --device_path {{ sds_disks|join(',') }}
    --force_device_takeover
    --i_am_sure
  retries: 10
  delay: 5
  register: add_devices
  until: add_devices.rc == 0
  delegate_to: "{{ powerflex_config_ip }}"
  when: 
    - sds_disks|length > 0
    - cluster_interface != rebuild_interface

- name: add SDS when a single network is defined
  command: >
    scli --add_sds
    --sds_ip {{ hostvars[inventory_hostname]['ansible_'+cluster_interface]['ipv4']['address'] }},
    --storage_pool_name {{ storage_pool }}
    --sds_name {{ hostvars[inventory_hostname]['ansible_hostname'] }}
    --protection_domain_name {{ protection_domain }}
    --device_path {{ sds_disks|join(',') }}
    --force_device_takeover
    --i_am_sure
  retries: 10
  delay: 5
  register: add_devices
  until: add_devices.rc == 0
  delegate_to: "{{ powerflex_config_ip }}"
  when:
    - sds_disks|length > 0
    - cluster_interface == rebuild_interface

