apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ocsfspvc
  namespace: ocs
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: ocs-storagecluster-cephfs
  volumeMode: Filesystem
