apiVersion: v1
kind: Pod
metadata:
  name: ocsfspod
  namespace: ocs
spec:
  containers:
  - name: task-pv-container
    image: image-registry.openshift-image-registry.svc:5000/openshift/nginxnfs
    ports:
      - containerPort: 80
        name: "http-server"
    volumeMounts:
      - mountPath: "/usr/share/nginx/html"
        name: dynamic-ocs-fs-vol
  volumes:
    - name: dynamic-ocs-fs-vol
      persistentVolumeClaim:
        claimName: ocsfspvc
