apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ocsrbdpvc
  namespace: ocs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: ocs-storagecluster-ceph-rbd
  volumeMode: Filesystem
