apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dynamic-fc-unity-pvc
  namespace: unity
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 6Gi
  storageClassName: unity-fc
