apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dynamic-iscsi-unity-pvc
  namespace: unity
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 7Gi
  storageClassName: unity-iscsi
