apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dynamic-nfs-unity-pvc
  namespace: unity
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 4Gi
  storageClassName: unity-nfs
