apiVersion: v1
kind: Pod
metadata:
  name: dynamic-nfs-unity-pod
  namespace: unity
spec:
  containers:
  - name: task-pv-container
    image: nginx:latest
    ports:
      - containerPort: 80
        name: "http-server"
    volumeMounts:
      - mountPath: "/usr/share/nginx/html"
        name: dy-nfs-unity
  volumes:
    - name: dy-nfs-unity
      persistentVolumeClaim:
        claimName: dynamic-nfs-unity-pvc
