apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dynamic-new-iscsi-unity-pvc
  namespace: unity
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: unity-iscsi
