apiVersion: v1
kind: Pod
metadata:
  name: image-registry-pod
  namespace: unity
spec:
  containers:
  - name: task-pv-container
    image: image-registry.openshift-image-registry.svc:5000/openshift/nginxnfs
