apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dynamic-nfs-image-registry
  namespace: openshift-image-registry
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 120Gi
  storageClassName: unity-nfs
