apiVersion: v1
kind: Pod
metadata:
  name: restore-pod
  namespace: unity
spec:
  containers:
  - name: task-pv-container
    #image: nginx:latest
    image: image-registry.openshift-image-registry.svc:5000/openshift/nginxnfs
    ports:
      - containerPort: 80
        name: "http-server"
    volumeMounts:
      - mountPath: "/usr/share/nginx/html"
        name: restore-pvc
  volumes:
    - name: restore-pvc
      persistentVolumeClaim:
        claimName: unity-restore
