apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unity-restore
spec:
  storageClassName: unity-iscsi
  dataSource:
    name: unity-snapshot
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 7Gi
