apiVersion: snapshot.storage.k8s.io/v1beta1
kind: VolumeSnapshot
metadata:
  name: unity-snapshot
  namespace: unity
spec:
  volumeSnapshotClassName: unity-snap
  source:
    persistentVolumeClaimName: dynamic-iscsi-unity-pvc
