apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dynamic-fc-powermax-pvc
  namespace: powermax
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 6Gi
  storageClassName: powermax-bronze
