apiVersion: v1
kind: Pod
metadata:
  name: restore-pod
  namespace: powermax
spec:
  containers:
  - name: task-pv-container
    image: nginx:latest
    ports:
      - containerPort: 80
        name: "http-server"
    volumeMounts:
      - mountPath: "/usr/share/nginx/html"
        name: dy-fc-snapshot
  volumes:
    - name: dy-fc-snapshot
      persistentVolumeClaim:
        claimName: powermax-restore
