apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: powermax-restore
spec:
  storageClassName: powermax-bronze
  dataSource:
    name: powermax-snapshot
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 6Gi
