heat_template_version: rocky
description: >
  Bond and VLAN configuration for compute nodes. comment14_0: ' The values of the following parameters are overridden by the
  entries in' comment15_0: ' network-environment.yaml'
parameters:
  ControlPlaneIp:
    default: ''
    description: IP address/subnet on the ctlplane network
    type: string
  ExternalIpSubnet:
    default: ''
    description: IP address/subnet on the external network
    type: string
  InternalApiIpSubnet:
    default: ''
    description: IP address/subnet on the internal API network
    type: string
  StorageIpSubnet:
    default: ''
    description: IP address/subnet on the storage network
    type: string
  StorageMgmtIpSubnet:
    default: ''
    description: IP address/subnet on the storage mgmt network
    type: string
  TenantIpSubnet:
    default: ''
    description: IP address/subnet on the tenant network
    type: string
  ManagementIpSubnet: # Only populated when including environments/network-management.yaml
    default: ''
    description: IP address/subnet on the management network
    type: string
  ExternalNetworkVlanID:
    default: 10
    description: Vlan ID for the external network traffic.
    type: number
  InternalApiNetworkVlanID:
    default: 20
    description: Vlan ID for the internal_api network traffic.
    type: number
  StorageNetworkVlanID:
    default: 30
    description: Vlan ID for the storage network traffic.
    type: number
  TenantNetworkVlanID:
    default: 50
    description: Vlan ID for the tenant network traffic.
    type: number
  ManagementNetworkVlanID:
    default: 60
    description: Vlan ID for the management network traffic.
    type: number
  ControlPlaneSubnetCidr:
    default: ''
    description: >
      The subnet CIDR of the control plane network. (The parameter is
      automatically resolved from the ctlplane subnet's cidr attribute.)
    type: string
  ControlPlaneNetCidr:
    description: Control plane/provisioning network and mask
    type: string
    default: ''
  ControlPlaneStaticRoutes:
    default: []
    description: >
      Routes for the ctlplane network traffic.
      JSON route e.g. [{'destination':'10.0.0.0/16', 'nexthop':'10.0.0.1'}]
      Unless the default is changed, the parameter is automatically resolved
      from the subnet host_routes attribute.
    type: json
  StorageInterfaceRoutes:
    default: []
    description: >
      Routes for the storage network traffic.
      JSON route e.g. [{'destination':'10.0.0.0/16', 'nexthop':'10.0.0.1'}]
      Unless the default is changed, the parameter is automatically resolved
      from the subnet host_routes attribute.
    type: json
  InternalApiInterfaceRoutes:
    default: []
    description: >
      Routes for the internal_api network traffic.
      JSON route e.g. [{'destination':'10.0.0.0/16', 'nexthop':'10.0.0.1'}]
      Unless the default is changed, the parameter is automatically resolved
      from the subnet host_routes attribute.
    type: json
  TenantInterfaceRoutes:
    default: []
    description: >
      Routes for the tenant network traffic.
      JSON route e.g. [{'destination':'10.0.0.0/16', 'nexthop':'10.0.0.1'}]
      Unless the default is changed, the parameter is automatically resolved
      from the subnet host_routes attribute.
    type: json
  ControlPlaneDefaultRoute: # Override this via parameter_defaults
    description: The default route of the control plane network.
    type: string
  ExternalInterfaceDefaultRoute: # Not used by default in this template
    default: ''
    description: The default route of the external network.
    type: string
  ManagementInterfaceDefaultRoute: # Commented out by default in this template
    default: unset
    description: The default route of the management network.
    type: string
  DnsServers: # Override this via parameter_defaults
    default: []
    description: A list of DNS servers (2 max for some implementations) that will be added to resolv.conf.
    type: comma_delimited_list
  EC2MetadataIp: # Override this via parameter_defaults
    description: The IP address of the EC2 metadata server.
    type: string
  ComputeProvisioningInterface:
    default: eno3
    description: Provisioning interface name
    type: string
  ComputeBond0Interface1:
    default: eno1
    description: Bond 0 interface 1 name
    type: string
  ComputeBond0Interface2:
    default: ens3f0
    description: Bond 0 interface 2 name
    type: string
  ComputeBond1Interface1:
    default: eno2
    description: Bond 1 interface 1 name
    type: string
  ComputeBond1Interface2:
    default: ens3f1
    description: Bond 1 interface 2 name
    type: string
  ComputeBondInterfaceOptions:
    default: mode=802.3ad miimon=100 xmit_hash_policy=layer3+4 lacp_rate=1
    description: The bonding_options string for the bond interface.
    type: string
  ComputeSriovInterface1:
    default: ens2f0
    description: SRIOV Interface 1 name
    type: string
  ComputeSriovInterface2:
    default: ens3f0
    description: SRIOV Interface 2 name
    type: string
  NumSriovVfs: # Override this via parameter_defaults
    default: 4
    description: Number of SRIOV Virtual Functions.
    type: number
  ControlPlaneMtu:
    default: 1500
    description: The maximum transmission unit (MTU) size(in bytes) that is
      guaranteed to pass through the data path of the segments in the network.
      (The parameter is automatically resolved from the ctlplane network's mtu attribute.)
    type: number
  ExternalMtu: # Override this via parameter_defaults
    default: 1500
    description: MTU value for this network.
    type: number
  InternalApiMtu: # Override this via parameter_defaults
    default: 1500
    description: MTU value for this network.
    type: number
  StorageMtu: # Override this via parameter_defaults
    default: 1500
    description: MTU value for this network.
    type: number
  StorageMgmtMtu: # Override this via parameter_defaults
    default: 1500
    description: MTU value for this network.
    type: number
  TenantMtu: # Override this via parameter_defaults
    default: 1500
    description: MTU value for this network.
    type: number
  ProvisioningMtu: # Override this via parameter_defaults
    default: 1500
    description: MTU value for this network.
    type: number
  ManagementMtu: # Override this via parameter_defaults
    default: 1500
    description: MTU value for this network.
    type: number
  DefaultBondMtu: # Override this via parameter_defaults
    default: 9000
    description: MTU value for this network.
    type: number

resources:
  OsNetConfigImpl:
    type: OS::Heat::SoftwareConfig
    properties:
      group: script
      config:
        str_replace:
          template:
            get_file: /usr/share/openstack-tripleo-heat-templates/network/scripts/run-os-net-config.sh
          params:
            $network_config:
              network_config:
              - type: interface
                name:
                  get_param: ComputeProvisioningInterface
                mtu:
                  get_param: ProvisioningMtu
                use_dhcp: false
                dns_servers:
                  get_param: DnsServers
                addresses:
                - ip_netmask:
                    list_join:
                    - /
                    - - get_param: ControlPlaneIp
                      - get_param: ControlPlaneSubnetCidr
                routes:
                - ip_netmask: 169.254.169.254/32
                  next_hop:
                    get_param: EC2MetadataIp
                - default: true
                  next_hop:
                    get_param: ControlPlaneDefaultRoute
              - type: ovs_bridge
                name: br-tenant
                mtu:
                  get_param: DefaultBondMtu
                members:
                - type: linux_bond
                  name: bond0
                  bonding_options:
                    get_param: ComputeBondInterfaceOptions
                  mtu:
                    get_param: DefaultBondMtu
                  members:
                  - type: interface
                    name:
                      get_param: ComputeBond0Interface1
                    mtu:
                      get_param: DefaultBondMtu
                    primary: true
                  - type: interface
                    name:
                      get_param: ComputeBond0Interface2
                    mtu:
                      get_param: DefaultBondMtu
                - type: vlan
                  device: bond0
                  vlan_id:
                    get_param: TenantNetworkVlanID
                  mtu:
                    get_param: TenantMtu
                  addresses:
                  - ip_netmask:
                      get_param: TenantIpSubnet
                - type: vlan
                  device: bond0
                  vlan_id:
                    get_param: InternalApiNetworkVlanID
                  mtu:
                    get_param: InternalApiMtu
                  addresses:
                  - ip_netmask:
                      get_param: InternalApiIpSubnet
              - type: ovs_bridge
                name: br-bond1
                mtu:
                  get_param: DefaultBondMtu
                members:
                - type: linux_bond
                  name: bond1
                  bonding_options:
                    get_param: ComputeBondInterfaceOptions
                  mtu:
                    get_param: DefaultBondMtu
                  members:
                  - type: interface
                    name:
                      get_param: ComputeBond1Interface1
                    mtu:
                      get_param: DefaultBondMtu
                    primary: true
                  - type: interface
                    name:
                      get_param: ComputeBond1Interface2
                    mtu:
                      get_param: DefaultBondMtu
                - type: vlan
                  device: bond1
                  vlan_id:
                    get_param: StorageNetworkVlanID
                  mtu:
                    get_param: StorageMtu
                  addresses:
                  - ip_netmask:
                      get_param: StorageIpSubnet
              - type: sriov_pf
                name:
                  get_param: ComputeSriovInterface1
                mtu:
                  get_param: DefaultBondMtu
                numvfs:
                      get_param: NumSriovVfs
                use_dhcp: false
                defroute: false
                nm_controlled: true
                hotplug: true
                promisc: false
              - type: sriov_pf
                name:
                  get_param: ComputeSriovInterface2
                mtu:
                  get_param: DefaultBondMtu
                numvfs:
                      get_param: NumSriovVfs
                use_dhcp: false
                defroute: false
                nm_controlled: true
                hotplug: true
                promisc: false

outputs:
  OS::stack_id:
    description: The OsNetConfigImpl resource.
    value:
      get_resource: OsNetConfigImpl
