---
- name: 'manage the chrony service'
  become: yes
  service: 
    name: '{{ chrony_service_name }}'
    enabled: '{{ chrony_service_enabled }}'
    state: '{{ chrony_service_state }}'
  tags: 'chrony-service'
