heat_template_version: 2015-04-30

description: >
  Bond and VLAN configuration for compute nodes.

# The values of the following parameters are overridden by the entries in
# network-environment.yaml
parameters:
  ExternalIpSubnet:
    default: ''
    description: IP address/subnet on the external network
    type: string
  InternalApiIpSubnet:
    default: ''
    description: IP address/subnet on the internal API network
    type: string
  StorageIpSubnet:
    default: ''
    description: IP address/subnet on the storage network
    type: string
  StorageMgmtIpSubnet:
    default: ''
    description: IP address/subnet on the storage mgmt network
    type: string
  TenantIpSubnet:
    default: ''
    description: IP address/subnet on the tenant network
    type: string
  InternalApiNetworkVlanID:
    default: 20
    description: Vlan ID for the internal_api network traffic.
    type: number
  StorageNetworkVlanID:
    default: 30
    description: Vlan ID for the storage network traffic.
    type: number

  # CHANGEME: If you wish to use different bonding modes for different roles,
  # then specify the appropriate bonding options in the "default" line below
  # for the compute role, otherwise ignore this entry.
  BondInterfaceOvsOptions:
    default: ''
    description: The ovs_options string for the bond interface. Set things like
                 lacp=active and/or bond_mode=balance-slb using this option.
    type: string

resources:
  OsNetConfigImpl:
    type: OS::Heat::StructuredConfig
    properties:
      group: os-apply-config
      config:
        os_net_config:
          network_config:
            -
              type: ovs_bridge
              name: br-tenant
              members:
                -
                  type: ovs_bond
                  name: bond0
                  ovs_options: {get_param: BondInterfaceOvsOptions}
                  members:
                    -
                      type: interface
                      # CHANGEME: Change the interface name on the following
                      # line to an interface to include in bond0
                      name: em1
                      primary: true
                    -
                      type: interface
                      # CHANGEME: Change the interface name on the following
                      # line to an interface to include in bond0
                      name: p3p1
                -
                  type: vlan
                  device: bond0
                  vlan_id: {get_param: InternalApiNetworkVlanID}
                  addresses:
                    -
                      ip_netmask: {get_param: InternalApiIpSubnet}
            -
              type: ovs_bridge
              name: br-bond1
              members:
                -
                  type: ovs_bond
                  name: bond1
                  ovs_options: {get_param: BondInterfaceOvsOptions}
                  members:
                    -
                      type: interface
                      # CHANGEME: Change the interface name on the following
                      # line to an interface to include in bond1
                      name: em2
                      primary: true
                    -
                      type: interface
                      # CHANGEME: Change the interface name on the following
                      # line to an interface to include in bond1
                      name: p3p2
                  addresses:
                    -
                      ip_netmask: {get_param: StorageIpSubnet}

outputs:
  OS::stack_id:
    description: The OsNetConfigImpl resource.
    value: {get_resource: OsNetConfigImpl}
