# A Heat environment file which can be used to enable a
# cinder Dell Storage Center backend configured via puppet

resource_registry:
  OS::TripleO::ControllerExtraConfigPre: HOME/pilot/templates/overcloud/puppet/extraconfig/pre_deploy/controller/cinder-dellsc.yaml

parameter_defaults:
  #Enable this to add Dell Storage Center as a backend
  CinderEnableDellScBackend: false
  
  #Name to give this backend
  CinderDellScBackendName: 'tripleo_dellsc'

  #IP address of Enterprise Manager
  CinderDellScSanIp: 'CHANGEME'
  
  #Login user name of Enterprise Manager
  CinderDellScSanLogin: 'CHANGEME'
  
  #Enterprise Manager password
  CinderDellScSanPassword: 'CHANGEME'

  #The Storage Center serial number
  CinderDellScSsn: 'CHANGEME'

  #The Storage Center ISCSI IP Address
  CinderDellScIscsiIpAddress: 'CHANGEME'

  #The Storage Center ISCSI port
  CinderDellScIscsiPort: '3260'

  #The Enterprise Manager API Port
  CinderDellScApiPort: '3033'

  #Server folder to place new server definitions
  CinderDellScServerFolder: 'dellsc_server'
  
  #Volume folder to place created volumes definitions
  CinderDellScVolumeFolder: 'dellsc_volume'
