# Copyright (c) 2016-2020 Dell Inc. or its subsidiaries.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# resource_registry:
#   OS::TripleO::Network::Ports::NetVipMap: ./overcloud/network/ports/net_ip_map.yaml
#   OS::TripleO::Network::Ports::ExternalVipPort: ./overcloud/network/ports/noop.yaml
#   OS::TripleO::Network::Ports::InternalApiVipPort: ./overcloud/network/ports/noop.yaml
#   OS::TripleO::Network::Ports::StorageVipPort: ./overcloud/network/ports/noop.yaml
#   OS::TripleO::Network::Ports::StorageMgmtVipPort: ./overcloud/network/ports/noop.yaml


parameter_defaults:

  ControlFixedIPs: [{'ip_address':'192.168.120.250'}]
  InternalApiVirtualFixedIPs: [{'ip_address':'192.168.140.250'}]
  PublicVirtualFixedIPs: [{'ip_address':'100.67.59.51'}]
  StorageVirtualFixedIPs: [{'ip_address':'192.168.170.250'}]
  StorageMgmtVirtualFixedIPs: [{'ip_address':'192.168.120.249'}]
  RedisVirtualFixedIPs: [{'ip_address':'192.168.140.250'}]
