# Copyright (c) 2018 Dell Inc. or its subsidiaries.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

resource_registry:
  OS::TripleO::Controller::Net::SoftwareConfig: ./controller.yaml
  OS::TripleO::ComputeHCI::Net::SoftwareConfig: ./computeHCI.yaml


parameter_defaults:
  # CHANGEME: Change the interface names in the following lines for the
  # controller nodes provisioning interface and to include in the controller
  # nodes bonds
  ControllerProvisioningInterface: em3
  ControllerBond0Interface1: p1p1
  ControllerBond0Interface2: p2p1
  ControllerBond1Interface1: p1p2
  ControllerBond1Interface2: p2p2
  # The bonding mode to use for controller nodes
  ControllerBondInterfaceOptions: mode=802.3ad miimon=100 xmit_hash_policy=layer3+4 lacp_rate=1

  # CHANGEME: Change the interface names in the following lines for the
  # compute nodes provisioning interface and to include in the compute
  # nodes bonds
  ComputeHCIProvisioningInterface: em3
  ComputeHCIBond0Interface1: p3p1
  ComputeHCIBond0Interface2: p2p1
  ComputeHCIBond1Interface1: p3p2
  ComputeHCIBond1Interface2: p2p2
  ComputeHCIBond2Interface1: p6p1
  ComputeHCIBond2Interface2: p7p1
  # The bonding mode to use for compute nodes
  ComputeHCIBondInterfaceOptions: mode=802.3ad miimon=100 xmit_hash_policy=layer3+4 lacp_rate=1
