---
# handlers file for proxy
- name: restart HAPROXY
  systemd:
    name: haproxy
    state: restarted
  listen: "haproxy restart"

- name: restart keepalived
  systemd:
    name: keepalived
    state: restarted
  listen: "keepalived restart"
