apiVersion: v1
kind: Pod
metadata:
  name: velero-bkpone-pod
  namespace: test-velero
spec:
  containers:
  - name: task-pv-container
    image: image-registry.openshift-image-registry.svc:5000/openshift/nginxnfs
    ports:
      - containerPort: 80
        name: "http-server"
    volumeMounts:
      - mountPath: "/usr/share/nginx/html"
        name: velero
  volumes:
    - name: velero
      persistentVolumeClaim:
        claimName: velero-bkpone-pvc
