#!/bin/bash

MEDIUM_URL="http://CHANGEME_IP/CHANGEME_PATH"
START_IP_RANGE="CHANGEME_SUBNET_START_IP"
END_IP_RANGE="CHANGEME_SUBNET_END_IP"
GATEWAY_IP="CHANGEME_FOREMAN_PROVISIONING_IP"
SUBSCRIPTION_MANAGER_USERNAME="CHANGEME_USERNAME"
SUBSCRIPTION_MANAGER_PASSWORD="CHANGEME_PASSWORD"

# CHANGEME: Customize the interface for the IDRAC NIC below as needed
IDRAC_NIC="em4"

# CHANGEME: Customize the interfaces for the bonds below as needed
CONTROLLER_BONDS="( [bond0]=\"em1 p1p1\" [bond1]=\"em2 p1p2\" )"
COMPUTE_BONDS="( [bond0]=\"em1 p1p1\" [bond1]=\"em2 p1p2\" )"
STORAGE_BONDS="( [bond0]=\"em1 p4p1\" [bond1]=\"em2 p4p2\" )"
