apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dynamic-nfs-isilon-pvc
  namespace: isilon
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 4Gi
  storageClassName: isilon-nfs
