apiVersion: v1
kind: Pod
metadata:
  name: restore-pod
  namespace: isilon
spec:
  containers:
  - name: task-pv-container
    image: nginx:latest
    ports:
      - containerPort: 80
        name: "http-server"
    volumeMounts:
      - mountPath: "/usr/share/nginx/html"
        name: restore-pvc
  volumes:
    - name: restore-pvc
      persistentVolumeClaim:
        claimName: isilon-restore
