apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: isilon-restore
spec:
  storageClassName: isilon-nfs
  dataSource:
    name: isilon-snapshot
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 4Gi
