apiVersion: snapshot.storage.k8s.io/v1beta1
kind: VolumeSnapshot
metadata:
  name: isilon-snapshot
  namespace: isilon
spec:
  volumeSnapshotClassName: isilon-snap
  source:
    persistentVolumeClaimName: dynamic-nfs-isilon-pvc
