## A Heat environment that can be used to deploy SR-IOV
resource_registry:
  OS::TripleO::Services::NeutronSriovAgent: {{NeutronSriovAgent}}
  OS::TripleO::Services::NeutronSriovHostConfig: {{NeutronSriovHostConfig}}
parameter_defaults:
  NeutronMechanismDrivers: ['sriovnicswitch', 'openvswitch']
  NeutronEnableIsolatedMetadata: true
  NeutronEnableForceMetadata: true
  NeutronTunnelTypes: ''
  NumSriovVfs: {{parameter_defaults.NumSriovVfs}}
  {%- for key, val in parameter_defaults.items() %}
    {%- if key.endswith("Parameters") %}
  {{key}}:
      {%- for _key, _val in val.items() %}
        {%- if _key == "NeutronPhysicalDevMappings" %}
    {{_key}}:
          {%- for item in _val %}
      - {{item}}
          {%- endfor %}
        {%- endif %}
        {%- if _key == "NovaPCIPassthrough" %}
    {{_key}}:
          {%- for dev in _val %}
      - devname: {{dev.devname}}
        physical_network: {{dev.physical_network}}
          {%- endfor %}
        {%- endif %}
      {%- endfor %}
    {%- endif %}
  {%- endfor %}
