# Copyright (c) 2016-2018 Dell Inc. or its subsidiaries.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

heat_template_version: 2015-04-30

description: >
  Bond and VLAN configuration for compute nodes.

# The values of the following parameters are overridden by the entries in
# network-environment.yaml
parameters:
  ControlPlaneIp:
    default: ''
    description: IP address/subnet on the ctlplane network
    type: string
  ExternalIpSubnet:
    default: ''
    description: IP address/subnet on the external network
    type: string
  InternalApiIpSubnet:
    default: ''
    description: IP address/subnet on the internal API network
    type: string
  StorageIpSubnet:
    default: ''
    description: IP address/subnet on the storage network
    type: string
  StorageMgmtIpSubnet:
    default: ''
    description: IP address/subnet on the storage mgmt network
    type: string
  TenantIpSubnet:
    default: ''
    description: IP address/subnet on the tenant network
    type: string
  ManagementIpSubnet: # Only populated when including environments/network-management.yaml
    default: ''
    description: IP address/subnet on the management network
    type: string
  ExternalNetworkVlanID:
    default: 10
    description: Vlan ID for the external network traffic.
    type: number
  InternalApiNetworkVlanID:
    default: 20
    description: Vlan ID for the internal_api network traffic.
    type: number
  StorageNetworkVlanID:
    default: 30
    description: Vlan ID for the storage network traffic.
    type: number
  TenantNetworkVlanID:
    default: 50
    description: Vlan ID for the tenant network traffic.
    type: number
  ManagementNetworkVlanID:
    default: 60
    description: Vlan ID for the management network traffic.
    type: number
  ControlPlaneSubnetCidr: # Override this via parameter_defaults
    default: '24'
    description: The subnet CIDR of the control plane network.
    type: string
  ControlPlaneDefaultRoute: # Override this via parameter_defaults
    description: The default route of the control plane network.
    type: string
  ExternalInterfaceDefaultRoute: # Not used by default in this template
    default: '10.0.0.1'
    description: The default route of the external network.
    type: string
  ManagementInterfaceDefaultRoute: # Commented out by default in this template
    default: unset
    description: The default route of the management network.
    type: string
  DnsServers: # Override this via parameter_defaults
    default: []
    description: A list of DNS servers (2 max for some implementations) that will be added to resolv.conf.
    type: comma_delimited_list
  EC2MetadataIp: # Override this via parameter_defaults
    description: The IP address of the EC2 metadata server.
    type: string
  ComputeProvisioningInterface:
    default: 'em3'
    description: Provisioning interface name
    type: string
  ComputeBond0Interface1:
    default: 'em1'
    description: Bond 0 interface 1 name
    type: string
  ComputeBond0Interface2:
    default: 'p1p1'
    description: Bond 0 interface 2 name
    type: string
  ComputeBond1Interface1:
    default: 'em2'
    description: Bond 1 interface 1 name
    type: string
  ComputeBond1Interface2:
    default: 'p1p2'
    description: Bond 1 interface 2 name
    type: string
  ComputeBondInterfaceOptions:
    default: 'mode=802.3ad miimon=100 xmit_hash_policy=layer3+4 lacp_rate=1'
    description: The bonding_options string for the bond interface.
    type: string
  ComputeOvsDpdkInterface1:
    default: 'p2p1'
    description: Dpdk Interface 1 name
    type: string
  ComputeOvsDpdkInterface2:
    default: 'p3p1'
    description: Dpdk Interface 2 name
    type: string
  ComputeOvsDpdkInterface3:
    default: 'p2p2'
    description: Dpdk Interface 3 name
    type: string
  ComputeOvsDpdkInterface4:
    default: 'p3p2'
    description: Dpdk Interface 4 name
    type: string
  BondInterfaceOvsOptions:
    default: 'bond_mode=balance-tcp lacp=active'
    description: The bonding_options string for the bond interface. Set things
                 like 'bond_mode=balance-tcp lacp=active' using this option.
    type: string


resources:
  OsNetConfigImpl:
    type: OS::Heat::StructuredConfig
    properties:
      group: os-apply-config
      config:
        os_net_config:
          network_config:
            -
              type: interface
              name: {get_param: ComputeProvisioningInterface}
              use_dhcp: false
              dns_servers: {get_param: DnsServers}
              addresses:
                -
                  ip_netmask:
                    list_join:
                      - '/'
                      - - {get_param: ControlPlaneIp}
                        - {get_param: ControlPlaneSubnetCidr}
              routes:
                -
                  ip_netmask: 169.254.169.254/32
                  next_hop: {get_param: EC2MetadataIp}
                -
                  default: true
                  next_hop: {get_param: ControlPlaneDefaultRoute}
            -
              type: linux_bond
              name: bond0
              bonding_options: {get_param: ComputeBondInterfaceOptions}
              members:
                -
                  type: interface
                  name: {get_param: ComputeBond0Interface1}
                  primary: true
                -
                  type: interface
                  name: {get_param: ComputeBond0Interface2}
            -
              type: vlan
              device: bond0
              vlan_id: {get_param: TenantNetworkVlanID}
              addresses:
                -
                  ip_netmask: {get_param: TenantIpSubnet}
            -
              type: vlan
              device: bond0
              vlan_id: {get_param: InternalApiNetworkVlanID}
              addresses:
                -
                  ip_netmask: {get_param: InternalApiIpSubnet}
                        


            -
              type: ovs_user_bridge
              name: br-tenant
              use_dhcp: false
              members:
                -
                  type: ovs_dpdk_bond
                  name: ovs_dpdk_bond10
                  ovs_options: {get_param: BondInterfaceOvsOptions}
                  members:
                    -
                      type: ovs_dpdk_port
                      name: dpdk0
                      members:
                        -
                          type: interface
                          name: {get_param: ComputeOvsDpdkInterface1}
                    -
                      type: ovs_dpdk_port
                      name: dpdk1
                      members:
                        -
                          type: interface
                          name: {get_param: ComputeOvsDpdkInterface2}
            -
              type: interface
              name: {get_param: ComputeOvsDpdkInterface3}
              use_dhcp: false
            -
              type: interface
              name: {get_param: ComputeOvsDpdkInterface4}
              use_dhcp: false
            -
              type: linux_bond
              name: bond1
              bonding_options: {get_param: ComputeBondInterfaceOptions}
              members:
                -
                  type: interface
                  name: {get_param: ComputeBond1Interface1}
                  primary: true
                -
                  type: interface
                  name: {get_param: ComputeBond1Interface2}
            -
              type: vlan
              device: bond1
              vlan_id: {get_param: StorageNetworkVlanID}
              addresses:
                -
                  ip_netmask: {get_param: StorageIpSubnet}
outputs:
  OS::stack_id:
    description: The OsNetConfigImpl resource.
    value: {get_resource: OsNetConfigImpl}

